/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tsetlin.proto */

#ifndef PROTOBUF_C_tsetlin_2eproto__INCLUDED
#define PROTOBUF_C_tsetlin_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Clause Clause;
typedef struct ClauseCompressed ClauseCompressed;
typedef struct Tsetlin Tsetlin;


/* --- enums --- */

typedef enum _ModelType {
  MODEL_TYPE__INFERENCE = 0,
  MODEL_TYPE__TRAINING = 1,
  MODEL_TYPE__COMPRESSED = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MODEL_TYPE)
} ModelType;

/* --- messages --- */

struct  Clause
{
  ProtobufCMessage base;
  uint32_t n_feature;
  uint32_t n_state;
  size_t n_data;
  uint32_t *data;
};
#define CLAUSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&clause__descriptor) \
    , 0, 0, 0,NULL }


struct  ClauseCompressed
{
  ProtobufCMessage base;
  uint32_t n_pos_literal;
  uint32_t n_neg_literal;
  uint32_t n_state;
  size_t n_position;
  uint32_t *position;
  size_t n_data;
  uint32_t *data;
};
#define CLAUSE_COMPRESSED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&clause_compressed__descriptor) \
    , 0, 0, 0, 0,NULL, 0,NULL }


struct  Tsetlin
{
  ProtobufCMessage base;
  uint32_t n_class;
  uint32_t n_feature;
  uint32_t n_clause;
  uint32_t n_state;
  ModelType model_type;
  size_t n_clauses;
  Clause **clauses;
  size_t n_clauses_compressed;
  ClauseCompressed **clauses_compressed;
};
#define TSETLIN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tsetlin__descriptor) \
    , 0, 0, 0, 0, MODEL_TYPE__INFERENCE, 0,NULL, 0,NULL }


/* Clause methods */
void   clause__init
                     (Clause         *message);
size_t clause__get_packed_size
                     (const Clause   *message);
size_t clause__pack
                     (const Clause   *message,
                      uint8_t             *out);
size_t clause__pack_to_buffer
                     (const Clause   *message,
                      ProtobufCBuffer     *buffer);
Clause *
       clause__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   clause__free_unpacked
                     (Clause *message,
                      ProtobufCAllocator *allocator);
/* ClauseCompressed methods */
void   clause_compressed__init
                     (ClauseCompressed         *message);
size_t clause_compressed__get_packed_size
                     (const ClauseCompressed   *message);
size_t clause_compressed__pack
                     (const ClauseCompressed   *message,
                      uint8_t             *out);
size_t clause_compressed__pack_to_buffer
                     (const ClauseCompressed   *message,
                      ProtobufCBuffer     *buffer);
ClauseCompressed *
       clause_compressed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   clause_compressed__free_unpacked
                     (ClauseCompressed *message,
                      ProtobufCAllocator *allocator);
/* Tsetlin methods */
void   tsetlin__init
                     (Tsetlin         *message);
size_t tsetlin__get_packed_size
                     (const Tsetlin   *message);
size_t tsetlin__pack
                     (const Tsetlin   *message,
                      uint8_t             *out);
size_t tsetlin__pack_to_buffer
                     (const Tsetlin   *message,
                      ProtobufCBuffer     *buffer);
Tsetlin *
       tsetlin__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tsetlin__free_unpacked
                     (Tsetlin *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Clause_Closure)
                 (const Clause *message,
                  void *closure_data);
typedef void (*ClauseCompressed_Closure)
                 (const ClauseCompressed *message,
                  void *closure_data);
typedef void (*Tsetlin_Closure)
                 (const Tsetlin *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    model_type__descriptor;
extern const ProtobufCMessageDescriptor clause__descriptor;
extern const ProtobufCMessageDescriptor clause_compressed__descriptor;
extern const ProtobufCMessageDescriptor tsetlin__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_tsetlin_2eproto__INCLUDED */
