/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tsetlin.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tsetlin.pb-c.h"
void   clause__init
                     (Clause         *message)
{
  static const Clause init_value = CLAUSE__INIT;
  *message = init_value;
}
size_t clause__get_packed_size
                     (const Clause *message)
{
  assert(message->base.descriptor == &clause__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t clause__pack
                     (const Clause *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &clause__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t clause__pack_to_buffer
                     (const Clause *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &clause__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Clause *
       clause__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Clause *)
     protobuf_c_message_unpack (&clause__descriptor,
                                allocator, len, data);
}
void   clause__free_unpacked
                     (Clause *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &clause__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   clause_compressed__init
                     (ClauseCompressed         *message)
{
  static const ClauseCompressed init_value = CLAUSE_COMPRESSED__INIT;
  *message = init_value;
}
size_t clause_compressed__get_packed_size
                     (const ClauseCompressed *message)
{
  assert(message->base.descriptor == &clause_compressed__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t clause_compressed__pack
                     (const ClauseCompressed *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &clause_compressed__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t clause_compressed__pack_to_buffer
                     (const ClauseCompressed *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &clause_compressed__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClauseCompressed *
       clause_compressed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClauseCompressed *)
     protobuf_c_message_unpack (&clause_compressed__descriptor,
                                allocator, len, data);
}
void   clause_compressed__free_unpacked
                     (ClauseCompressed *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &clause_compressed__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tsetlin__init
                     (Tsetlin         *message)
{
  static const Tsetlin init_value = TSETLIN__INIT;
  *message = init_value;
}
size_t tsetlin__get_packed_size
                     (const Tsetlin *message)
{
  assert(message->base.descriptor == &tsetlin__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tsetlin__pack
                     (const Tsetlin *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tsetlin__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tsetlin__pack_to_buffer
                     (const Tsetlin *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tsetlin__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tsetlin *
       tsetlin__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tsetlin *)
     protobuf_c_message_unpack (&tsetlin__descriptor,
                                allocator, len, data);
}
void   tsetlin__free_unpacked
                     (Tsetlin *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tsetlin__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor clause__field_descriptors[3] =
{
  {
    "n_feature",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Clause, n_feature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_state",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Clause, n_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Clause, n_data),
    offsetof(Clause, data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned clause__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = n_feature */
  1,   /* field[1] = n_state */
};
static const ProtobufCIntRange clause__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor clause__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Clause",
  "Clause",
  "Clause",
  "",
  sizeof(Clause),
  3,
  clause__field_descriptors,
  clause__field_indices_by_name,
  1,  clause__number_ranges,
  (ProtobufCMessageInit) clause__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor clause_compressed__field_descriptors[5] =
{
  {
    "n_pos_literal",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClauseCompressed, n_pos_literal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_neg_literal",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClauseCompressed, n_neg_literal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_state",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClauseCompressed, n_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ClauseCompressed, n_position),
    offsetof(ClauseCompressed, position),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ClauseCompressed, n_data),
    offsetof(ClauseCompressed, data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned clause_compressed__field_indices_by_name[] = {
  4,   /* field[4] = data */
  1,   /* field[1] = n_neg_literal */
  0,   /* field[0] = n_pos_literal */
  2,   /* field[2] = n_state */
  3,   /* field[3] = position */
};
static const ProtobufCIntRange clause_compressed__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor clause_compressed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClauseCompressed",
  "ClauseCompressed",
  "ClauseCompressed",
  "",
  sizeof(ClauseCompressed),
  5,
  clause_compressed__field_descriptors,
  clause_compressed__field_indices_by_name,
  1,  clause_compressed__number_ranges,
  (ProtobufCMessageInit) clause_compressed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tsetlin__field_descriptors[7] =
{
  {
    "n_class",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Tsetlin, n_class),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_feature",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Tsetlin, n_feature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_clause",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Tsetlin, n_clause),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_state",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Tsetlin, n_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model_type",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Tsetlin, model_type),
    &model_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clauses",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Tsetlin, n_clauses),
    offsetof(Tsetlin, clauses),
    &clause__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clauses_compressed",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Tsetlin, n_clauses_compressed),
    offsetof(Tsetlin, clauses_compressed),
    &clause_compressed__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tsetlin__field_indices_by_name[] = {
  5,   /* field[5] = clauses */
  6,   /* field[6] = clauses_compressed */
  4,   /* field[4] = model_type */
  0,   /* field[0] = n_class */
  2,   /* field[2] = n_clause */
  1,   /* field[1] = n_feature */
  3,   /* field[3] = n_state */
};
static const ProtobufCIntRange tsetlin__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor tsetlin__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Tsetlin",
  "Tsetlin",
  "Tsetlin",
  "",
  sizeof(Tsetlin),
  7,
  tsetlin__field_descriptors,
  tsetlin__field_indices_by_name,
  1,  tsetlin__number_ranges,
  (ProtobufCMessageInit) tsetlin__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue model_type__enum_values_by_number[3] =
{
  { "INFERENCE", "MODEL_TYPE__INFERENCE", 0 },
  { "TRAINING", "MODEL_TYPE__TRAINING", 1 },
  { "COMPRESSED", "MODEL_TYPE__COMPRESSED", 2 },
};
static const ProtobufCIntRange model_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex model_type__enum_values_by_name[3] =
{
  { "COMPRESSED", 2 },
  { "INFERENCE", 0 },
  { "TRAINING", 1 },
};
const ProtobufCEnumDescriptor model_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ModelType",
  "ModelType",
  "ModelType",
  "",
  3,
  model_type__enum_values_by_number,
  3,
  model_type__enum_values_by_name,
  1,
  model_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
